apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.yml: |
    mqtt:
      host: mosquitto.ix-mosquitto.svc.cluster.local
      # Optional: port (default: shown below)
      port: 1883
      # Optional: topic prefix (default: shown below)
      # NOTE: must be unique if you are running multiple instances
      topic_prefix: frigate
      # Optional: client id (default: shown below)
      # NOTE: must be unique if you are running multiple instances
      client_id: frigate
      
    # Optional: Detectors configuration. Defaults to a single CPU detector
    detectors:
      coral:
        type: edgetpu
        device: usb
      cpu1:
        type: cpu
        num_threads: 2
    ffmpeg:
      global_args: -hide_banner -loglevel debug
    cameras:
      name: camera1