apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.yml: |
    mqtt:
      # Required: host name
      host: {{ .Values.frigate.mqtt.host }}
      # Optional: port (default: shown below)
      port: {{ .Values.frigate.mqtt.port }}
      # Optional: topic prefix (default: shown below)
      # NOTE: must be unique if you are running multiple instances
      topic_prefix: frigate
      # Optional: client id (default: shown below)
      # NOTE: must be unique if you are running multiple instances
      client_id: frigate
    detectors:
      coral:
        type: edgecpu
        device: usb
    cameras:
      camera_1:
        ffmpeg:
          inputs:
            -path: rtsp://10.0.10.10:554/rtsp
             roles:
               - detect
               - rtmp

        rtmp:
          enabled: False
        detect:
          width: 1280
          height: 720
