apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  config.yml: |
    mqtt:
      # Required: host name
      host: public.mqtthq.com
      # Optional: port (default: shown below)
      port: 1883
      # Optional: topic prefix (default: shown below)
      # NOTE: must be unique if you are running multiple instances
      topic_prefix: frigate
      # Optional: client id (default: shown below)
      # NOTE: must be unique if you are running multiple instances
      client_id: frigate
      
    # Optional: Detectors configuration. Defaults to a single CPU detector
    detectors:
      coral:
        type: edgetpu
        device: usb
      cpu1:
        type: cpu
        num_threads: 2
    cameras:
{{- range .Values.frigate.cameras }}
      # Required: name of the camera
      {{ .name }}:
        objects:
          # Optional: list of objects to track from labelmap.txt (default: shown below)
          track:
            {{- range .objects.track }}
              - {{ . }}
            {{- end }}
        detect:
          width: {{ .detect.width }}
          height: {{ .detect.height }}
{{- end }}